import os
from dotenv import load_dotenv
from google import genai

# Load environment variables from .env file
# This allows us to keep sensitive configuration outside the Python source code
load_dotenv()
api_key = os.getenv("GEMINI_API_KEY")
gemini_model = os.getenv("GEMINI_MODEL")

# Validate the Gemini API key is available before creating the Gemini client
if not api_key:
    raise ValueError("GEMINI_API_KEY is not configured")

# Create the Gemini API client
client = genai.Client(api_key=api_key)

# Define the generation configuration
# max_output_tokens: Limits the max amount of output generated by Gemini
# thinking_level: controls the amount of model reasoning effort used for the request
generation_config = {
    'max_output_tokens': 1000,
    'thinking_level': 'medium',
}

student_name = input("Student name: ")
education = input("Education: ")
skills = input("Your current technical skills (comma separated) : ")
projects = input("Projects (Comma separated) : ")
experience = input("Experience / Internship if any : ")
target_role = input("Target Job Role: ")

user_input = input("Enter your query: ")

# Context Engineering
student_context = f"""
STUDENT PROFILE

Name: {student_name}
Education: {education}
Technical Skills: {skills}
Projects: {projects}
Experience/Internship: {experience}
Target Job Role: {target_role}
"""

# Prompt Engineering
career_prompt = f"""
ROLE:
You are CareerTwin, You are an AI career advisor for post-grad students

CONTEXT:
CareerTwin helps students understand software engineering career paths, required technical skills, learning priorities, projects and interview preparation.

TASK:
Answer the student's career related question clearly and practically. Give revommendations that are relevant to the student's career goal

CONSTRAINTS:
- Do not provide unrelated information
- Do not assume skills that the stduent has not mentioned
- Prefer practical and actionable recommendations
- Keep the response concise and easy to understand

{student_context}

STUDENT QUESTION:
{user_input}
"""

# Send our request to Gemini.
response = client.interactions.create(
    model = gemini_model,
    input = career_prompt,
    generation_config=generation_config,
)
print("==== GEMINI ====")
print(response.output_text)